<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Promosi kelas baru yang direkomendasikan untuk kamu_svg-inline--fa fa-w-16 foawe fa-check-circle css-mqha09</name>
   <tag></tag>
   <elementGuidId>0fa22e21-a3e4-4543-bdc2-17d537063ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//svg[@aria-hidden = 'true']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>check-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-w-16 foawe fa-check-circle css-mqha09</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 512 512</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-ChangeNotificationPage&quot;)/div[@class=&quot;flex flex-column&quot;]/div[@class=&quot;css-1r6cy3i&quot;]/div[@class=&quot;flex flex-column w-100 flex w-100 css-mglkre&quot;]/div[1]/div[@class=&quot;w-100 pv5 pl5-ns&quot;]/div[@class=&quot;flex flex-column ph5-ns ph2 pt2 pb4 w-100 css-6k51kr&quot;]/div[@class=&quot;mt4-ns mt3 ph4-ns ph3 w-100&quot;]/div[1]/table[@class=&quot;f6 w-100 center css-t8mv2l&quot;]/tbody[@class=&quot;lh-copy&quot;]/tr[@class=&quot;css-1akth7c&quot;]/td[@class=&quot;pa3 bb b--near-white&quot;]/span[@class=&quot;css-10v6l23&quot;]/div[@class=&quot;outline-0 css-jgdgyw&quot;]/svg[@class=&quot;svg-inline--fa fa-w-16 foawe fa-check-circle css-mqha09&quot;]</value>
   </webElementProperties>
</WebElementEntity>
